version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile_app
    container_name: graphql_app
    volumes:
      - ./app/:/app/
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    build:
      context: .
      dockerfile: ./Dockerfile_db
    container_name: graphql_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    env_file:
      - ./.env



