FROM python:3.10.10-alpine3.17

WORKDIR /app

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev nano

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt
EXPOSE 5000

RUN echo '1 1 1 * * python3 /app/clean_tokens_task.py' >> /etc/crontabs/root
RUN echo '0 0 * * * python3 /app/finish_orders_task.py' >> /etc/crontabs/root
RUN echo '# END OF CRON JOBS' >> /etc/crontabs/root

CMD crond && python3 ./app.py