FROM python:3.10.10-alpine3.17

WORKDIR /app

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev nano

RUN pip install --upgrade pip

COPY app/ .
RUN pip install -r requirements.txt
RUN cd hotel_business && pip install .

EXPOSE 8000

RUN echo '0 0 * * * python3 /app/clean_carts_task.py' >> /etc/crontabs/root
RUN echo '0 0 * * * python3 /app/finish_orders_task.py' >> /etc/crontabs/root
RUN echo '# END OF CRON JOBS' >> /etc/crontabs/root

CMD crond && python3 ./app.py